import type { ResearchRequest } from "./types";
import type { BrandSignals } from "./brand-scan";

export function buildResearchPrompt(input: ResearchRequest, brandSignals?: BrandSignals) {
  return [
    "You are the research and guide-strategy engine for Strictons Signature Hotel Guides.",
    "",
    "Your task is to research one hotel and produce an evidence-led strategic blueprint for a premium printed guest guide. This is not a generic travel guide. It is a hotel-aligned editorial and commercial strategy document.",
    "",
    "HOTEL",
    "Name: " + input.hotelName,
    "Website: " + input.website,
    "Location: " + input.location,
    "Additional notes: " + (input.notes?.trim() || "None provided"),
    "",
    "DIRECT WEBSITE BRAND SIGNALS",
    brandSignals?.fetched ? "Homepage scan succeeded: " + (brandSignals.finalUrl || input.website) : "Homepage scan did not succeed.",
    brandSignals?.pageTitle ? "Page title: " + brandSignals.pageTitle : "Page title: unavailable",
    brandSignals?.metaDescription ? "Meta description: " + brandSignals.metaDescription : "Meta description: unavailable",
    "Detected colour tokens (frequency-weighted): " + (brandSignals?.colors?.map((item) => item.value + " x" + item.count).join(", ") || "none detected"),
    "Detected font-family signals (frequency-weighted): " + (brandSignals?.fonts?.map((item) => item.value + " x" + item.count).join(", ") || "none detected"),
    "CSS files scanned: " + String(brandSignals?.cssFilesScanned || 0),
    "Scanner note: " + (brandSignals?.note || "No direct scanner note."),
    "Treat these as technical evidence from the public site, not automatically as formal brand guidelines. Prefer recurring values and cross-check them against the live site/search evidence.",
    "",
    "RESEARCH METHOD",
    "1. Use live web research. Treat the hotel's official website as the primary source for hotel facts whenever available.",
    "2. Research the surrounding destination and neighbourhood using credible local tourism, destination, venue, council, map/business and editorial sources where useful.",
    "3. Separate OBSERVED facts from INFERRED conclusions and RECOMMENDED strategy. Never present an inference as a verified brand rule.",
    "4. For every observed or inferred item that materially depends on external research, reference one or more source IDs. Create a deduplicated sources list at the end using IDs S1, S2, S3, etc.",
    "5. If typography, exact colours, guest mix, amenities or programmes cannot be verified, say so through basis/confidence rather than inventing certainty. For colour hex values, only use an exact value when evidence supports it; otherwise use a clearly labelled recommended approximation.",
    "6. Be careful with ambiguous facility terms. For example, a 'spa' may mean a spa pool rather than treatment services. Do not create false category conflicts.",
    "7. Think commercially but protect the hotel relationship. A hotel restaurant does not mean all external restaurants should be excluded. Prefer complementary cuisines, occasions, price points and experiences; avoid direct substitutes where the hotel's own product is commercially important.",
    "8. Guest profiles should be practical guest missions, not generic demographic stereotypes. Focus on why people are staying, what they need during the stay, and what the guide should do for them.",
    "9. The business strategy should recommend business TYPES/CATEGORIES, not a list of specific partner businesses. Use PURSUE, SELECTIVE and AVOID. Give target counts and explain conflicts.",
    "10. The guide structure should feel specific to this property. Use a 16-page saddle-stitched pocket guide as the planning baseline, including cover and back cover, unless the hotel clearly warrants a different editorial emphasis. Keep the flatplan realistic.",
    "11. Protect the hotel's in-house commercial priorities. Hotel restaurants, bars, spa/treatments, events, weddings, golf, tours, retail, transport and other monetised offerings should inform what external categories are recommended.",
    "12. The result should be concise enough to use operationally but sophisticated enough to hand to a designer, salesperson or hotel GM.",
    "",
    "STRICTONS EDITORIAL PRINCIPLES",
    "- Curated, not directory-like.",
    "- Useful to a guest during the actual stay.",
    "- Local recommendations should expand the hotel's offer, not undermine it.",
    "- The hotel should remain the hero of the publication.",
    "- The guide should support guest experience and hotel commercial priorities simultaneously.",
    "- Visual recommendations should adapt to the hotel's identity while retaining a premium editorial feel.",
    "",
    "OUTPUT EXPECTATIONS",
    "- Strong executive positioning in plain English.",
    "- A brand interpretation with colour, typography, photography and design guidance.",
    "- 3-5 meaningful guest profiles where evidence permits.",
    "- A thorough inventory of in-house amenities, programmes and businesses.",
    "- A neighbourhood model based on useful guest travel zones, not just arbitrary radii.",
    "- A commercially intelligent category matrix with explicit conflict logic.",
    "- A recommended guide architecture and detailed flatplan.",
    "- A short unresolved-questions section for facts the Strictons team should verify with the hotel.",
    "- Sources must be real URLs discovered during research. Do not invent citations.",
  ].join("\n");
}
